backend:
  name: git-gateway
  branch: master
pages:
  enabled: true
  config:
    label: Page
    delete: false
    editor:
      preview: true
over_format: true
media_folder: source/images
public_folder: /images
collections:
  - name: posts
    label: Post
    folder: source/_posts
    sort: 'date:desc'
    create: true
    fields: &ref_0
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
        dateFormat: YYYY-MM-DD
        timeFormat: 'HH:mm:ss'
        format: 'YYYY-MM-DD HH:mm:ss'
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Categories
        name: categories
        widget: list
        required: false
      - label: Body
        name: body
        widget: markdown
        required: false
      - label: Permalink
        name: permalink
        widget: string
        required: false
      - label: Comments
        name: comments
        widget: boolean
        default: true
        required: false
  - label: Page
    name: pages
    delete: false
    files:
      - name: archives-index.md
        label: archives
        file: source\archives\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: about-index.md
        label: About
        file: source\about\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: categories-index.md
        label: Categories
        file: source\categories\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: like-index.md
        label: I like it...
        file: source\like\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: project-index.md
        label: Project
        file: source\project\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: tags-index.md
        label: Tags
        file: source\tags\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: topics-index.md
        label: Topics
        file: source\topics\index.md
        editor:
          preview: true
        fields: *ref_0
